builds:
  - main: ./src/
    binary: ./bin/helm-migrate
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml