builds:
  - main: ./cmd/helm-migrate
    binary: ./bin/helm-migrate
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
      - GO111MODULE=auto
archives:
  - id: tar
    format: tar.gz
    files:
      - plugin.yaml