name: migrate
version: "0.0.6"
usage: "backup restore"
description: "Backup and restore helm charts in entire cluster"
command: "$HELM_PLUGIN_DIR/bin/helm-migrate"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"