name: migrate
usage: "backup restore"
description: "Backup and restore helm charts in entire cluster"
command: "$HELM_PLUGIN_DIR/helm-migrate"
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/src/helm-migrate"
